# DUT parameters
DUT:
  id: "ciscoNexus9336-FX2"  # no space!
  port_file: "ports.yml"
  type: "router"
  needs_commit: False  # Does OS require commit to apply configs

# Measurement parameters
measurement_time_s:   6      # in seconds
configuration_time_s: 0      # in seconds, also serves as warm-up interval for the traffic generation
wait_factor_short_s: 1.5  # Factors that gets multiplied with the number of ports impacted
wait_factor_long_s: 2.8
sampling_interval_ms: 1000     # in milliseconds
random_seed:                  # leave empty for uncontrolled seed

# External dependencies
pinpoint:
  binary: "/local/home/psteinebrunn/pinpoint/build/pinpoint"
  #binary: "/home/user/Workspace/Projects/green-networking/PowerProfilingTofino/pinpoint/build/pinpoint"
  workload: # currently unused
serial_port: "/dev/ttyUSB0"
baudrate: 9600
counter_1: mcp:dev0ch1
counter_2: mcp:dev0ch2

