# DUT parameters
DUT:
  id: "ciscoNexus9336-FX2"  # no space!
  port_file: "ports.yml"
  transceivers: "LR" # Passive Copper Cable
  type: "router"
  needs_commit: False  # Does OS require commit to apply configs
  manual_speed_setting: False  # two steps to change port speeds

# Measurement parameters
measurement_time_s:   3      # in seconds
configuration_time_s: 0      # in seconds, also serves as warm-up interval for the traffic generation
sampling_interval_ms: 1000     # in milliseconds
random_seed:                  # leave empty for uncontrolled seed

# External dependencies
pinpoint:
  # binary: "/local/home/jacobr/workspace/pinpoint/build/pinpoint"
  binary: "/home/user/Workspace/Projects/green-networking/PowerProfilingTofino/pinpoint/build/pinpoint"
  workload: # currently unused
serial_port: "/dev/ttyUSB0"
baudrate: 9600
