# DUT parameters
DUT:
  id: 
  port_file: "ports.yml"
  transceivers: 
  type: 
  needs_commit:  # Does OS require commit to apply configs
  
# Measurement parameters
measurement_time_s:         # in seconds
configuration_time_s:       # in seconds, also serves as warm-up interval for the traffic generation
wait_factor_short_s:   # Factors that gets multiplied with the number of ports impacted
wait_factor_long_s: 
sampling_interval_ms:      # in milliseconds
random_seed:                  # leave empty for uncontrolled seed

# External dependencies
pinpoint:
  binary: 
  workload: # currently unused
serial_port: "/dev/ttyUSB0"
baudrate: 9600
