# DUT parameters
DUT:
  id: "cisco8201-32FH"  # no space!
  port_file: "ports.yml"
  transceivers: "PCC" # Passive Copper Cable
  type: "router"
  needs_commit: True  # Does OS require commit to apply configs

# Measurement parameters
measurement_time_s:   30      # in seconds
configuration_time_s: 30      # in seconds
sampling_interval_ms: 500     # in milliseconds
random_seed:                  # leave empty for uncontrolled seed

# External dependencies
pinpoint:
  binary: "/home/user/Workspace/Projects/green-networking/PowerProfilingTofino/pinpoint/build/pinpoint"
  # binary: "/local/home/jacobr/workspace/pinpoint/build/pinpoint"
  workload: # currently unused
serial_port: "/dev/ttyUSB0"
baudrate: 115200
