# DUT parameters
DUT:
  id: "aristaDCS-7280CR3K-32D4"  # no space!
  port_file: "ports.yml"
  transceivers: "FR4" # Passive Copper Cable
  type: "router"
  needs_commit: false  # Does OS require commit to apply configs
  manual_speed_setting: False  # two steps to change port speeds

# Measurement parameters
measurement_time_s:   30      # in seconds
configuration_time_s: 15      # in seconds
sampling_interval_ms: 500     # in milliseconds
random_seed:                  # leave empty for uncontrolled seed

# External dependencies
pinpoint:
  binary: "/home/user/Workspace/Projects/green-networking/PowerProfilingTofino/pinpoint/build/pinpoint"
  # binary: "/local/home/jacobr/workspace/pinpoint/build/pinpoint"
  workload: # currently unused
serial_port: "/dev/ttyUSB0"
baudrate: 9600
